In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv(r"building data/2zone_Supermarket.csv", encoding="gbk")
df.rename(columns={'Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep)': 'outdoor temperature'}, inplace=True)
df

,Date/Time,outdoor temperature,BACKROOM:Zone Total Internal Total Heating Rate [W](TimeStep),SALESFLOOR:Zone Total Internal Total Heating Rate [W](TimeStep),BACKROOM LIGHTS 1:Lights Electricity Rate [W](TimeStep),SALESFLOOR LIGHTS 1:Lights Electricity Rate [W](TimeStep),BACKROOM ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 2:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 3:Electric Equipment Electricity Rate [W](TimeStep),BACKROOM:Zone Windows Total Heat Gain Rate [W](TimeStep),SALESFLOOR:Zone Windows Total Heat Gain Rate [W](TimeStep),BACKROOM:Zone Air Temperature [C](TimeStep),BACKROOM:Zone Air System Sensible Heating Rate [W](TimeStep),BACKROOM:Zone Air System Sensible Cooling Rate [W](TimeStep),SALESFLOOR:Zone Air Temperature [C](TimeStep),SALESFLOOR:Zone Air System Sensible Heating Rate [W](TimeStep),SALESFLOOR:Zone Air System Sensible Cooling Rate [W](TimeStep)
0,01/01 00:15:00,0.75,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.998740,892.817384,0.0,21.982192,6691.603054,0.0
1,01/01 00:30:00,1.50,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.013591,804.598616,0.0,21.996581,5018.467095,0.0
2,01/01 00:45:00,2.25,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.022188,862.534193,0.0,21.999341,6149.798386,0.0
3,01/01 01:00:00,3.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.030167,870.297423,0.0,21.999872,6336.278048,0.0
4,01/01 01:15:00,2.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.037435,880.578178,0.0,21.999975,6569.112118,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,12/31 23:00:00,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.692433,832.741763,0.0,21.972241,4008.808827,0.0
35036,12/31 23:15:00,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.680000,813.834794,0.0,21.902768,3945.687681,0.0
35037,12/31 23:30:00,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.670310,798.329552,0.0,21.840934,3921.633981,0.0
35038,12/31 23:45:00,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.662201,784.411293,0.0,21.783584,3912.588600,0.0
35039,12/31 24:00:00,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.654249,771.619048,0.0,21.729630,3908.265396,0.0

In [8]:
df = df.reset_index(drop=True)
numerical_cols = df.select_dtypes(include='number').columns
df = df[numerical_cols]
df

,outdoor temperature,BACKROOM:Zone Total Internal Total Heating Rate [W](TimeStep),SALESFLOOR:Zone Total Internal Total Heating Rate [W](TimeStep),BACKROOM LIGHTS 1:Lights Electricity Rate [W](TimeStep),SALESFLOOR LIGHTS 1:Lights Electricity Rate [W](TimeStep),BACKROOM ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 2:Electric Equipment Electricity Rate [W](TimeStep),SALESFLOOR ELECEQ 3:Electric Equipment Electricity Rate [W](TimeStep),BACKROOM:Zone Windows Total Heat Gain Rate [W](TimeStep),SALESFLOOR:Zone Windows Total Heat Gain Rate [W](TimeStep),BACKROOM:Zone Air Temperature [C](TimeStep),BACKROOM:Zone Air System Sensible Heating Rate [W](TimeStep),BACKROOM:Zone Air System Sensible Cooling Rate [W](TimeStep),SALESFLOOR:Zone Air Temperature [C](TimeStep),SALESFLOOR:Zone Air System Sensible Heating Rate [W](TimeStep),SALESFLOOR:Zone Air System Sensible Cooling Rate [W](TimeStep)
0,0.75,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.998740,892.817384,0.0,21.982192,6691.603054,0.0
1,1.50,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.013591,804.598616,0.0,21.996581,5018.467095,0.0
2,2.25,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.022188,862.534193,0.0,21.999341,6149.798386,0.0
3,3.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.030167,870.297423,0.0,21.999872,6336.278048,0.0
4,2.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,20.037435,880.578178,0.0,21.999975,6569.112118,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.692433,832.741763,0.0,21.972241,4008.808827,0.0
35036,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.680000,813.834794,0.0,21.902768,3945.687681,0.0
35037,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.670310,798.329552,0.0,21.840934,3921.633981,0.0
35038,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.662201,784.411293,0.0,21.783584,3912.588600,0.0
35039,0.00,10.5,9457.5,3.0,9000.0,7.5,0.0,0.0,300.0,0.0,0.0,19.654249,771.619048,0.0,21.729630,3908.265396,0.0

In [9]:
selected_df = pd.DataFrame({'outdoor temperature': df['outdoor temperature']})
col_to_sum = ['BACKROOM LIGHTS 1:Lights Electricity Rate [W](TimeStep)', 'SALESFLOOR LIGHTS 1:Lights Electricity Rate [W](TimeStep)', 
              'BACKROOM ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep)', 'SALESFLOOR ELECEQ 1:Electric Equipment Electricity Rate [W](TimeStep)', 
              'SALESFLOOR ELECEQ 2:Electric Equipment Electricity Rate [W](TimeStep)', 'SALESFLOOR ELECEQ 3:Electric Equipment Electricity Rate [W](TimeStep)']
selected_df['load'] = df[col_to_sum].sum(axis=1)
selected_df = selected_df.reset_index(drop=True)
n = selected_df
selected_df['date'] = selected_df.index // (24 * 4) # 15 min 一个间隔
selected_df['time'] = selected_df.index % (24 * 4)

selected_df['date'] = np.sin(selected_df['date'] * 2 * np.pi / 365)
selected_df['time'] = np.sin(selected_df['time'] * 2 * np.pi / (24*4))

selected_df

       outdoor temperature    load      date      time
0                     0.75  9310.5  0.000000  0.000000
1                     1.50  9310.5  0.000000  0.065403
2                     2.25  9310.5  0.000000  0.130526
3                     3.00  9310.5  0.000000  0.195090
4                     2.00  9310.5  0.000000  0.258819
...                    ...     ...       ...       ...
35035                 0.00  9310.5 -0.017213 -0.321439
35036                 0.00  9310.5 -0.017213 -0.258819
35037                 0.00  9310.5 -0.017213 -0.195090
35038                 0.00  9310.5 -0.017213 -0.130526
35039                 0.00  9310.5 -0.017213 -0.065403

[35040 rows x 4 columns]

In [10]:
selected_df.to_csv(r'building data/2zonesupermarket15.csv', index=False)

In [16]:
from pathlib import Path
import os

In [60]:
folder = Path(r"integrate2023")
csv_files = [p for p in folder.iterdir()]
key_col = "time"
dfs = []
for f in csv_files:
    # df = pd.read_csv(f, encoding='utf-8', encoding_errors='ignore')
    df = pd.read_csv(f, encoding='utf-8')
    key = df.columns[0]
    stem = f.stem
    df.set_index(key).add_suffix(f"_{stem}").pipe(dfs.append)

merged = pd.concat(dfs, axis=1)
merged.reset_index(inplace=True)

print(merged.shape)
merged['Time'] = pd.to_datetime(merged['Time'], format="%Y/%m/%d %H:%M")
min15_exact = merged[merged['Time'].dt.minute.isin([0, 15, 30, 45])].copy()
min15_exact = min15_exact.sort_values(by='Time')
min15_exact
# merged.set_index('Time')
# min15_exact = merged[merged.index.minute == 0 or merged.index.minute == 15 or merged.index.minute == 30 or merged.index.minute == 45]

(519670, 9)

,Time,RH (%)_Relative Humidity_2023,Wind Speed (m/s)_Wind_2023,Wind Direction (degree)_Wind_2023,Temp (Degree Celsius)_Temperature_2023,Rainfall(mm)_Rainfall_2023,Vis (km)_Visibility_2023,SLP (hPa)_Sea Level Pressure_2023,Irradiance (W/m2)_Irradiance_2023
0,2023-01-01 00:00:00,67.271,3.90040,13.5500,14.363,0.0,15.981,1009.86913,9.2760
15,2023-01-01 00:15:00,68.749,2.57040,337.7300,14.039,0.0,15.981,1009.89913,9.1652
30,2023-01-01 00:30:00,69.488,2.88380,356.8900,13.983,0.0,15.981,1009.94913,9.0547
45,2023-01-01 00:45:00,69.812,3.03610,9.3241,13.882,0.0,15.981,1009.92913,9.1651
60,2023-01-01 01:00:00,70.294,3.07190,354.0200,13.692,0.0,15.981,1009.89913,8.8340
...,...,...,...,...,...,...,...,...,...
519595,2023-12-31 22:45:00,72.832,3.32350,91.4440,18.876,0.0,13.912,1008.41913,0.0000
519610,2023-12-31 23:00:00,74.889,0.56583,335.9200,18.775,0.0,13.372,1008.46913,0.0000
519625,2023-12-31 23:15:00,76.480,0.77833,140.9400,18.565,0.0,13.253,1008.42913,0.0000
519640,2023-12-31 23:30:00,78.676,0.53010,100.7100,18.300,0.0,12.649,1008.51913,0.0000
519655,2023-12-31 23:45:00,79.874,1.03560,63.4670,18.289,0.0,12.526,1008.47913,0.0000

In [61]:
min15_exact.isna().stack()[lambda x: x].index.tolist()
min15_exact = min15_exact.interpolate(method='linear')
min15_exact.isna().sum()

Time                                      0
RH (%)_Relative Humidity_2023             0
Wind Speed (m/s)_Wind_2023                0
Wind Direction (degree)_Wind_2023         0
Temp (Degree Celsius)_Temperature_2023    0
Rainfall(mm)_Rainfall_2023                0
Vis (km)_Visibility_2023                  0
SLP (hPa)_Sea Level Pressure_2023         0
Irradiance (W/m2)_Irradiance_2023         0
dtype: int64

In [63]:
pv_file = Path(r"/Users/liqi/Library/CloudStorage/OneDrive-TheUniversityofHongKong-Connect/DRMPC with Prob Forecast/datasets/solar power Hong Kong rooftop/Time series dataset/PV generation dataset/PV stations without panel level optimizer/Site level dataset/CYT (Station 1).csv")
pv = pd.read_csv(pv_file)
pv["Time"] = pd.to_datetime(pv["Time"], format="%Y-%m-%d %H:%M:%S")
pv_select = pv[pv["Time"].dt.year == 2023]
pv_select

                     Time  generation(kWh)  power(W)
14543 2023-01-01 00:00:00              0.0       0.0
14544 2023-01-01 01:00:00              0.0       0.0
14545 2023-01-01 02:00:00              0.0       0.0
14546 2023-01-01 03:00:00              0.0       0.0
14547 2023-01-01 04:00:00              0.0       0.0
...                   ...              ...       ...
23298 2023-12-31 19:00:00              0.0       0.0
23299 2023-12-31 20:00:00              0.0       0.0
23300 2023-12-31 21:00:00              0.0       0.0
23301 2023-12-31 22:00:00              0.0       0.0
23302 2023-12-31 23:00:00              0.0       0.0

[8760 rows x 3 columns]

In [67]:
pv_select_indexed = pv_select.set_index('Time')
pv_15 = pv_select_indexed.resample('15T').interpolate(method='linear')

pv_15 = pv_15.reset_index()
last_row = pv_15.iloc[-1].copy()
for minute in [15, 30, 45]:
    new_row = last_row.copy()
    new_row['Time'] = pd.Timestamp('2023-12-31 23:00:00') + pd.Timedelta(minutes=minute)
    pv_15 = pd.concat([pv_15, pd.DataFrame([new_row])], ignore_index=True)

pv_15 = pv_15.sort_values('Time').reset_index(drop=True)
pv_15

/var/folders/0r/xrsnrkm50550l10wsrzlm0m00000gn/T/ipykernel_3576/2629143238.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  pv_15 = pv_select_indexed.resample('15T').interpolate(method='linear')

                     Time  generation(kWh)  power(W)
0     2023-01-01 00:00:00              0.0       0.0
1     2023-01-01 00:15:00              0.0       0.0
2     2023-01-01 00:30:00              0.0       0.0
3     2023-01-01 00:45:00              0.0       0.0
4     2023-01-01 01:00:00              0.0       0.0
...                   ...              ...       ...
35035 2023-12-31 22:45:00              0.0       0.0
35036 2023-12-31 23:00:00              0.0       0.0
35037 2023-12-31 23:15:00              0.0       0.0
35038 2023-12-31 23:30:00              0.0       0.0
35039 2023-12-31 23:45:00              0.0       0.0

[35040 rows x 3 columns]

In [68]:
pv_15.isna().sum()

Time               0
generation(kWh)    0
power(W)           0
dtype: int64

In [69]:
new = pd.merge(
    pv_15, min15_exact,
    on= 'Time',
    how = "outer"
).sort_values("Time").reset_index(drop=True)
new

,Time,generation(kWh),power(W),RH (%)_Relative Humidity_2023,Wind Speed (m/s)_Wind_2023,Wind Direction (degree)_Wind_2023,Temp (Degree Celsius)_Temperature_2023,Rainfall(mm)_Rainfall_2023,Vis (km)_Visibility_2023,SLP (hPa)_Sea Level Pressure_2023,Irradiance (W/m2)_Irradiance_2023
0,2023-01-01 00:00:00,0.0,0.0,67.271,3.90040,13.5500,14.363,0.0,15.981,1009.86913,9.2760
1,2023-01-01 00:15:00,0.0,0.0,68.749,2.57040,337.7300,14.039,0.0,15.981,1009.89913,9.1652
2,2023-01-01 00:30:00,0.0,0.0,69.488,2.88380,356.8900,13.983,0.0,15.981,1009.94913,9.0547
3,2023-01-01 00:45:00,0.0,0.0,69.812,3.03610,9.3241,13.882,0.0,15.981,1009.92913,9.1651
4,2023-01-01 01:00:00,0.0,0.0,70.294,3.07190,354.0200,13.692,0.0,15.981,1009.89913,8.8340
...,...,...,...,...,...,...,...,...,...,...,...
35035,2023-12-31 22:45:00,0.0,0.0,72.832,3.32350,91.4440,18.876,0.0,13.912,1008.41913,0.0000
35036,2023-12-31 23:00:00,0.0,0.0,74.889,0.56583,335.9200,18.775,0.0,13.372,1008.46913,0.0000
35037,2023-12-31 23:15:00,0.0,0.0,76.480,0.77833,140.9400,18.565,0.0,13.253,1008.42913,0.0000
35038,2023-12-31 23:30:00,0.0,0.0,78.676,0.53010,100.7100,18.300,0.0,12.649,1008.51913,0.0000
35039,2023-12-31 23:45:00,0.0,0.0,79.874,1.03560,63.4670,18.289,0.0,12.526,1008.47913,0.0000

In [70]:
new.isna().sum()

Time                                        0
generation(kWh)                             0
power(W)                                    0
RH (%)_Relative Humidity_2023             395
Wind Speed (m/s)_Wind_2023                395
Wind Direction (degree)_Wind_2023         395
Temp (Degree Celsius)_Temperature_2023    395
Rainfall(mm)_Rainfall_2023                395
Vis (km)_Visibility_2023                  395
SLP (hPa)_Sea Level Pressure_2023         395
Irradiance (W/m2)_Irradiance_2023         395
dtype: int64

In [72]:
# col_to_fill = ["RH (%)_Relative Humidity_2022", "Wind Speed (m/s)_Wind_2022", "Wind Direction (degree)_Wind_2022",
#               "Temp (Degree Celsius)_Temperature_2022", "Rainfall(mm)_Rainfall_2022",
#               "Vis (km)_Visibility_2022", "Irradiance (W/m2)_Irradiance_2022", "SLP (hPa)_Sea Level Pressure_2022"]
col_to_fill = ["RH (%)_Relative Humidity_2023", "Wind Speed (m/s)_Wind_2023", "Wind Direction (degree)_Wind_2023",
              "Temp (Degree Celsius)_Temperature_2023", "Rainfall(mm)_Rainfall_2023",
              "Vis (km)_Visibility_2023", "Irradiance (W/m2)_Irradiance_2023", "SLP (hPa)_Sea Level Pressure_2023"]
max_iter = 7
max_iter = 7

for col in col_to_fill:
    for iter in range(max_iter):
        new[col] = new[col].fillna(new[col].shift(96))
        if new[col].isna().sum() == 0:
            break

new.isna().sum()

Time                                      0
generation(kWh)                           0
power(W)                                  0
RH (%)_Relative Humidity_2023             0
Wind Speed (m/s)_Wind_2023                0
Wind Direction (degree)_Wind_2023         0
Temp (Degree Celsius)_Temperature_2023    0
Rainfall(mm)_Rainfall_2023                0
Vis (km)_Visibility_2023                  0
SLP (hPa)_Sea Level Pressure_2023         0
Irradiance (W/m2)_Irradiance_2023         0
dtype: int64

In [74]:
data = new.copy()
data["month"] = data["Time"].dt.month
data["day"] = data["Time"].dt.day
data["hour"] = data["Time"].dt.hour
data["min"] = data["Time"].dt.minute

cols = data.columns.tolist()
# new_cols = ['month', 'day', 'hour', 'min', 'generation(kWh)', 'RH (%)_Relative Humidity_2022', 
#             'Wind Speed (m/s)_Wind_2022', 'Wind Direction (degree)_Wind_2022', 'Temp (Degree Celsius)_Temperature_2022',
#             'Rainfall(mm)_Rainfall_2022', 'Vis (km)_Visibility_2022', 'Irradiance (W/m2)_Irradiance_2022',
#             'SLP (hPa)_Sea Level Pressure_2022']
new_cols = ['month', 'day', 'hour', 'min', 'generation(kWh)', 'RH (%)_Relative Humidity_2023', 
            'Wind Speed (m/s)_Wind_2023', 'Wind Direction (degree)_Wind_2023', 'Temp (Degree Celsius)_Temperature_2023',
            'Rainfall(mm)_Rainfall_2023', 'Vis (km)_Visibility_2023', 'Irradiance (W/m2)_Irradiance_2023',
            'SLP (hPa)_Sea Level Pressure_2023']
final_data = data[new_cols]
final_data

,month,day,hour,min,generation(kWh),RH (%)_Relative Humidity_2023,Wind Speed (m/s)_Wind_2023,Wind Direction (degree)_Wind_2023,Temp (Degree Celsius)_Temperature_2023,Rainfall(mm)_Rainfall_2023,Vis (km)_Visibility_2023,Irradiance (W/m2)_Irradiance_2023,SLP (hPa)_Sea Level Pressure_2023
0,1,1,0,0,0.0,67.271,3.90040,13.5500,14.363,0.0,15.981,9.2760,1009.86913
1,1,1,0,15,0.0,68.749,2.57040,337.7300,14.039,0.0,15.981,9.1652,1009.89913
2,1,1,0,30,0.0,69.488,2.88380,356.8900,13.983,0.0,15.981,9.0547,1009.94913
3,1,1,0,45,0.0,69.812,3.03610,9.3241,13.882,0.0,15.981,9.1651,1009.92913
4,1,1,1,0,0.0,70.294,3.07190,354.0200,13.692,0.0,15.981,8.8340,1009.89913
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,12,31,22,45,0.0,72.832,3.32350,91.4440,18.876,0.0,13.912,0.0000,1008.41913
35036,12,31,23,0,0.0,74.889,0.56583,335.9200,18.775,0.0,13.372,0.0000,1008.46913
35037,12,31,23,15,0.0,76.480,0.77833,140.9400,18.565,0.0,13.253,0.0000,1008.42913
35038,12,31,23,30,0.0,78.676,0.53010,100.7100,18.300,0.0,12.649,0.0000,1008.51913
35039,12,31,23,45,0.0,79.874,1.03560,63.4670,18.289,0.0,12.526,0.0000,1008.47913

In [75]:
output_name = "23solar_data15.csv"
final_data.columns = ["month", "day", "hour", "min", "generation", "RH", "WS", "WD", "Temp", "Rainfall", "Vis", "Irradiance", "SLP"]
final_data

,month,day,hour,min,generation,RH,WS,WD,Temp,Rainfall,Vis,Irradiance,SLP
0,1,1,0,0,0.0,67.271,3.90040,13.5500,14.363,0.0,15.981,9.2760,1009.86913
1,1,1,0,15,0.0,68.749,2.57040,337.7300,14.039,0.0,15.981,9.1652,1009.89913
2,1,1,0,30,0.0,69.488,2.88380,356.8900,13.983,0.0,15.981,9.0547,1009.94913
3,1,1,0,45,0.0,69.812,3.03610,9.3241,13.882,0.0,15.981,9.1651,1009.92913
4,1,1,1,0,0.0,70.294,3.07190,354.0200,13.692,0.0,15.981,8.8340,1009.89913
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,12,31,22,45,0.0,72.832,3.32350,91.4440,18.876,0.0,13.912,0.0000,1008.41913
35036,12,31,23,0,0.0,74.889,0.56583,335.9200,18.775,0.0,13.372,0.0000,1008.46913
35037,12,31,23,15,0.0,76.480,0.77833,140.9400,18.565,0.0,13.253,0.0000,1008.42913
35038,12,31,23,30,0.0,78.676,0.53010,100.7100,18.300,0.0,12.649,0.0000,1008.51913
35039,12,31,23,45,0.0,79.874,1.03560,63.4670,18.289,0.0,12.526,0.0000,1008.47913

In [76]:
final_data.to_csv(output_name, index=False)